controller_manager:
  ros__parameters:
    update_rate: 50 # Hz
    use_sim_time: true

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["right_front_wheel_joint", "left_front_wheel_joint"]

ackermann_steering_controller:
  ros__parameters:
    update_rate: 50 # Hz
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false
    rear_wheels_names: ["right_rear_wheel_joint", "left_rear_wheel_joint"]
    front_wheels_names: ["right_steering_hinge_joint", "left_steering_hinge_joint"]

    wheelbase: 0.26
    front_wheel_track: 0.18
    rear_wheel_track: 0.18
    front_wheels_radius: 0.032
    rear_wheels_radius: 0.032

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true